<a href="https://colab.research.google.com/github/VATHSAV2004/EDA_imp_libraries/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy
- short for numerical python

In [137]:
import numpy as np

In [138]:
import time

In [139]:
arr_list=[i for i in range(1,10000000,1)]

In [140]:
arr_list[:10]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [141]:
start_time=time.time()
sqr_arr=[x**2 for x in arr_list]
end_time=time.time()
print(start_time)
print(end_time)
print(end_time-start_time)

1755082579.3911548
1755082580.3310292
0.9398744106292725


In [142]:
sqr_arr[:10]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

# using numpy

In [143]:
arr_numpy=np.arange(1,10000000,1)

In [144]:
arr_numpy[:10]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [145]:
start_time=time.time()
sqr_numpy=arr_numpy**2
end_time=time.time()
print("time taken using numpy",end_time-start_time)

time taken using numpy 0.05575203895568848


# Creating ndarrays

In [146]:
l1=[1,2,3,4,5]


In [147]:
t1=(1,2,3,4,5)
a1=np.array(t1)
a1

array([1, 2, 3, 4, 5])

In [148]:
a1=np.array(range(1,11))
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [149]:
a1.shape

(10,)

In [150]:
a1.dtype

dtype('int64')

In [151]:
a1.ndim

1

In [152]:
a1=np.array([[1,2,3],[4,5,6]])
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [153]:
a1.shape

(2, 3)

In [154]:
a1.ndim

2

In [155]:
a1=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
a1

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [156]:
a1.shape

(2, 2, 2)

In [157]:
a1.ndim

3

In [158]:
a=np.array([1,2,3,4,5],dtype=float)
a

array([1., 2., 3., 4., 5.])

In [159]:
a.dtype

dtype('float64')

In [160]:
a=np.array([1.5,2.6,3.1,4.8,5.2],dtype=int)
a

array([1, 2, 3, 4, 5])

In [161]:
a.dtype

dtype('int64')

In [162]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [163]:
a=a.astype(float)
a

array([1., 2., 3., 4., 5.])

In [164]:
a=a.astype(int)
a

array([1, 2, 3, 4, 5])

In [165]:
a=a.astype(str)
a

array(['1', '2', '3', '4', '5'], dtype='<U21')

In [166]:
a.dtype

dtype('<U21')

## ndarrays by specifying range

In [167]:
a1=np.arange(0,10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [168]:
a1=np.arange(0,21,2)
a1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [169]:
a1=np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [170]:
a1=np.arange(10,dtype=float)
a1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

## creating ndarrays of ones

In [171]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [172]:
np.ones((3,2,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [173]:
np.ones((5,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## similarly nparrays of zeroes

In [174]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## creating ndarray of a specific value

In [175]:
np.full((4,5),fill_value=6)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

## creating an identity matrix

In [176]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [177]:
np.eye(5).dtype

dtype('float64')

# Operations on ndarrays

In [178]:
l=[1,2,3,4,5,6]
a1=np.array(l)
a1

array([1, 2, 3, 4, 5, 6])

In [179]:
# list
l2=[ele+3 for ele in l]
l2

[4, 5, 6, 7, 8, 9]

In [180]:
# Numpy
a1+3

array([4, 5, 6, 7, 8, 9])

In [181]:
a2=np.array([4,5,6,7,8,9])
a2

array([4, 5, 6, 7, 8, 9])

In [182]:
a1+a2

array([ 5,  7,  9, 11, 13, 15])

In [183]:
a1+[2,3,4,5,6,7]

array([ 3,  5,  7,  9, 11, 13])

In [184]:
a1*2

array([ 2,  4,  6,  8, 10, 12])

In [185]:
a1-3

array([-2, -1,  0,  1,  2,  3])

In [186]:
a1*a2

array([ 4, 10, 18, 28, 40, 54])

In [187]:
a1=np.array([2,4,6,8,10])
a3=a1/2
a3

array([1., 2., 3., 4., 5.])

In [188]:
a1//2

array([1, 2, 3, 4, 5])

In [189]:
a1%3

array([2, 1, 0, 2, 1])

In [190]:
a1**2

array([  4,  16,  36,  64, 100])

In [191]:
a2=np.array([2,3,4,5,6])
a1**a2

array([      4,      64,    1296,   32768, 1000000])

In [192]:
a1

array([ 2,  4,  6,  8, 10])

In [193]:
2/a1

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ])

In [194]:
type(2/a1)

numpy.ndarray

In [195]:
l1=[1,2,3,4,5]
# l1<4 gives error

In [196]:
a1=np.array([1,2,3,4,5,6])
a1<4

array([ True,  True,  True, False, False, False])

In [197]:
# list
l1=[9,1,4,5,3,6]
l2=[7,4,2,1,6,7]

l1<l2

False

In [198]:
a1=np.array([2,1,4,5,3,6])
a2=np.array([3,4,2,1,6,7])

In [199]:
a1<a2

array([ True,  True, False, False,  True,  True])

In [200]:
a1>a2

array([False, False,  True,  True, False, False])

In [201]:
a1<=a2

array([ True,  True, False, False,  True,  True])

In [202]:
a1>=a2

array([False, False,  True,  True, False, False])

In [203]:
a1==a2

array([False, False, False, False, False, False])

In [204]:
# operations between wo ndarrays not possible if shapes are not same

# Indexing and Slicing

In [205]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [206]:
a[0]

np.int64(0)

In [207]:
a[-1]

np.int64(9)

In [208]:
a[0:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [209]:
a[::]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [210]:
a[-8:-3]

array([2, 3, 4, 5, 6])

In [211]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [212]:
a[0:8:2]

array([0, 2, 4, 6])

# Reshape and Transpose

In [213]:
a=np.arange(16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [214]:
a.shape

(16,)

In [215]:
a.ndim

1

In [216]:
a=a.reshape((16,1))
a

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [217]:
a.shape

(16, 1)

In [218]:
a.ndim

2

In [219]:
a=a.reshape((1,16))
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [220]:
a.shape

(1, 16)

In [221]:
a.ndim

2

In [222]:
a.reshape((4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [223]:
a.reshape((2,2,4))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [224]:
a=np.arange(36)
a.reshape(1,36)
a.reshape(2,18)
a.reshape(3,12)
a.reshape(4,9)
a.reshape(6,6)
a.reshape(9,4)
a.reshape(12,3)
a.reshape(18,2)
a.reshape(36,1)
print("Possible 2D shape :",9)


Possible 2D shape : 9


In [225]:
a=np.arange(16).reshape((4,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [226]:
a.T # Transpose

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

# Functions

In [227]:
a=np.array([2,4,3,6,5,8,7,9,1,0])
a

array([2, 4, 3, 6, 5, 8, 7, 9, 1, 0])

In [228]:
a.sort()
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [229]:
s=np.square(a)
s

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [230]:
np.sqrt(s)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [231]:
np.sqrt(16)

np.float64(4.0)

In [232]:
a=np.array([8,27,64])
np.cbrt(a)

array([2., 3., 4.])

In [233]:
np.abs([-1,-2,3,-5,-6,-2,6])

array([1, 2, 3, 5, 6, 2, 6])

In [234]:
np.abs(-8)

np.int64(8)

In [235]:
abs(-8)

8

In [236]:
np.add([1,2,3],[4,5,6])

array([5, 7, 9])

In [237]:
np.subtract([4,5,6],[1,2,3])

array([3, 3, 3])

In [238]:
np.multiply([1,2,3],[2,3,4])

array([ 2,  6, 12])

In [239]:
a1=np.array([2,1,4,5,3,6])
a2=np.array([3,4,2,1,6,5])

In [240]:
np.maximum(a1,a2)

array([3, 4, 4, 5, 6, 6])

In [241]:
np.minimum(a1,a2)

array([2, 1, 2, 1, 3, 5])

In [242]:
np.greater(a1,a2)

array([False, False,  True,  True, False,  True])

In [243]:
np.less(a1,a2)

array([ True,  True, False, False,  True, False])

In [244]:
a1.mean()

np.float64(3.5)

In [245]:
np.mean(a1)

np.float64(3.5)

In [246]:
np.mean([1,2,3,4,5,6,7,8,9])

np.float64(5.0)

In [247]:
np.var([1,2,3,4,5,6,7,8,9])

np.float64(6.666666666666667)

In [248]:
np.std([1,2,3,4,5,6,7,8,9])

np.float64(2.581988897471611)

In [249]:
a1.var()

np.float64(2.9166666666666665)

In [250]:
a1.std()

np.float64(1.707825127659933)

In [251]:
a=np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [252]:
a.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [253]:
a.prod()

np.int64(3628800)

In [254]:
a.cumprod()

array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800])

In [255]:
a.min()

np.int64(1)

In [256]:
a.max()

np.int64(10)

In [257]:
a.sum()

np.int64(55)

In [258]:
a=np.arange(64).reshape(8,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [259]:
a.mean()

np.float64(31.5)

In [260]:
a.mean(axis=0) # column wise

array([28., 29., 30., 31., 32., 33., 34., 35.])

In [261]:
a.mean(axis=1) # row wise

array([ 3.5, 11.5, 19.5, 27.5, 35.5, 43.5, 51.5, 59.5])

In [262]:
a.std()

np.float64(18.472953201911167)

In [263]:
a.std(axis=0)

array([18.33030278, 18.33030278, 18.33030278, 18.33030278, 18.33030278,
       18.33030278, 18.33030278, 18.33030278])

In [264]:
a.std(axis=1)

array([2.29128785, 2.29128785, 2.29128785, 2.29128785, 2.29128785,
       2.29128785, 2.29128785, 2.29128785])

In [265]:
a.max()

np.int64(63)

In [266]:
a.max(axis=0)

array([56, 57, 58, 59, 60, 61, 62, 63])

In [267]:
a.max(axis=1)

array([ 7, 15, 23, 31, 39, 47, 55, 63])

In [268]:
x=np.array([10,30,80,20,40])
x

array([10, 30, 80, 20, 40])

In [269]:
np.argmax(x) # return index of max element

np.int64(2)

In [270]:
a1=np.array([2,1,5,4,3,5,6,7,3,10,2,3]).reshape(3,4)
a1

array([[ 2,  1,  5,  4],
       [ 3,  5,  6,  7],
       [ 3, 10,  2,  3]])

In [271]:
np.argmax(a1)

np.int64(9)

In [272]:
np.argmax(a1,axis=0)

array([1, 2, 1, 1])

In [273]:
a1.argmax(axis=1)

array([2, 3, 1])

In [274]:
np.argmin(a1,axis=0)

array([0, 0, 2, 2])

In [275]:
a1

array([[ 2,  1,  5,  4],
       [ 3,  5,  6,  7],
       [ 3, 10,  2,  3]])

In [276]:
a1.ravel()  # converts to single dimension

array([ 2,  1,  5,  4,  3,  5,  6,  7,  3, 10,  2,  3])

In [277]:
a2=a1.reshape(1,12)
a2

array([[ 2,  1,  5,  4,  3,  5,  6,  7,  3, 10,  2,  3]])

In [278]:
a2=a2.squeeze() # remove extra dimension
a2

array([ 2,  1,  5,  4,  3,  5,  6,  7,  3, 10,  2,  3])

In [279]:
a2.shape

(12,)

In [280]:
a2=a2.reshape(3,4,1)
a2

array([[[ 2],
        [ 1],
        [ 5],
        [ 4]],

       [[ 3],
        [ 5],
        [ 6],
        [ 7]],

       [[ 3],
        [10],
        [ 2],
        [ 3]]])

In [281]:
a2=a2.squeeze()
a2

array([[ 2,  1,  5,  4],
       [ 3,  5,  6,  7],
       [ 3, 10,  2,  3]])

In [282]:
a2.shape

(3, 4)

In [283]:
np.linspace(1,10,5) # generated 5 numbers with same distance

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [284]:
a=np.empty((2,3),dtype=int)
a  # random values generate array means emoty array already present data

array([[3, 4, 2],
       [1, 6, 5]])

# Determinants and Inverse

In [285]:
from numpy.linalg import det,inv,eig

In [286]:
a=np.array([4,3,7,9,2,3,9,6,1,4,7,6,11,4,8,7]).reshape((4,4))
a

array([[ 4,  3,  7,  9],
       [ 2,  3,  9,  6],
       [ 1,  4,  7,  6],
       [11,  4,  8,  7]])

In [287]:
det(a)

np.float64(527.0000000000006)

In [288]:
inv(a)

array([[-0.0170778 , -0.02087287, -0.07969639,  0.10815939],
       [-0.22580645, -0.38709677,  0.61290323,  0.09677419],
       [-0.10436433,  0.31688805, -0.15370019, -0.0056926 ],
       [ 0.27514231, -0.10815939, -0.04933586, -0.07590133]])

In [289]:
eig(a)

EigResult(eigenvalues=array([22.97864964,  3.76499269, -4.34011564, -1.40352668]), eigenvectors=array([[-0.51289911, -0.39468612,  0.5270535 ,  0.05108621],
       [-0.41676444,  0.52758299,  0.07812217, -0.85784205],
       [-0.37954612,  0.5045306 ,  0.33673147,  0.494701  ],
       [-0.64744625, -0.55796767, -0.77635266, -0.12949184]]))

# Concatenation

In [290]:
a1=np.arange(5)
a2=np.arange(5,10)

In [291]:
a1

array([0, 1, 2, 3, 4])

In [292]:
a2

array([5, 6, 7, 8, 9])

In [293]:
np.concatenate((a1,a2))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [294]:
np.concatenate((a1,a2),axis=0)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [295]:
a1=np.arange(12).reshape(4,3)
a2=np.arange(12,24).reshape(4,3)
print(a1)
print(a2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [296]:
np.concatenate((a1,a2),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [297]:
np.concatenate((a1,a2),axis=1)

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17],
       [ 6,  7,  8, 18, 19, 20],
       [ 9, 10, 11, 21, 22, 23]])

In [298]:
a1=a
a2=a.T
print(a1)
print()
print(a2)

[[ 4  3  7  9]
 [ 2  3  9  6]
 [ 1  4  7  6]
 [11  4  8  7]]

[[ 4  2  1 11]
 [ 3  3  4  4]
 [ 7  9  7  8]
 [ 9  6  6  7]]


In [299]:
np.concatenate((a1,a2),axis=0)

array([[ 4,  3,  7,  9],
       [ 2,  3,  9,  6],
       [ 1,  4,  7,  6],
       [11,  4,  8,  7],
       [ 4,  2,  1, 11],
       [ 3,  3,  4,  4],
       [ 7,  9,  7,  8],
       [ 9,  6,  6,  7]])

In [300]:
np.concatenate((a1,a2),axis=1)

array([[ 4,  3,  7,  9,  4,  2,  1, 11],
       [ 2,  3,  9,  6,  3,  3,  4,  4],
       [ 1,  4,  7,  6,  7,  9,  7,  8],
       [11,  4,  8,  7,  9,  6,  6,  7]])

# Random Numbers

In [301]:
np.random.randint(1,10)

7

In [302]:
np.random.randint(50)

29

In [303]:
np.random.randint(1,100,10)

array([67, 92, 12, 49,  5, 74, 16, 12, 65, 71])

In [304]:
np.random.randint(11,100,(10,10))

array([[61, 71, 70, 48, 22, 52, 11, 18, 36, 37],
       [53, 37, 92, 95, 13, 26, 83, 84, 33, 55],
       [66, 27, 71, 77, 81, 29, 61, 39, 82, 54],
       [35, 99, 25, 83, 91, 36, 96, 46, 94, 39],
       [82, 47, 28, 50, 92, 86, 19, 92, 13, 89],
       [62, 68, 63, 81, 29, 34, 36, 46, 45, 12],
       [56, 25, 59, 32, 29, 28, 74, 68, 45, 47],
       [12, 35, 65, 82, 70, 31, 85, 99, 20, 96],
       [60, 85, 23, 36, 18, 51, 73, 26, 80, 30],
       [85, 63, 35, 15, 35, 93, 96, 46, 80, 66]])

In [305]:
np.random.rand(10) #random number from 0 to 1

array([0.39226189, 0.19177645, 0.86446557, 0.02312516, 0.19660236,
       0.51298228, 0.9903973 , 0.30981725, 0.48046293, 0.79287977])

In [307]:
np.random.randn(10) # normal distribution random variables

array([ 0.27689196,  0.61451238,  0.93504119,  0.04502509,  0.83548112,
        0.7361701 , -1.6158669 , -0.08265678, -0.83334232,  0.70019642])

In [310]:
np.random.randn(10,10) #q) why not we give range here

array([[-0.15080778,  0.37100757, -1.51850958,  0.52987579,  0.84853522,
         0.53213361, -0.34602737,  0.19604245, -1.2489255 , -3.41368209],
       [ 0.45116082, -0.81768164, -0.30728303,  0.09759668, -0.70125735,
        -0.06631201, -0.47877006, -1.85618677,  0.20090197, -0.68452182],
       [-1.98116722, -0.95704571, -0.77883608, -0.48701859,  0.46398029,
         1.22769353, -0.41959879, -2.00682811, -0.03736877,  0.84446372],
       [ 0.1188288 ,  0.47609303, -0.21895707, -1.81606098,  0.5799234 ,
         0.788452  ,  1.21726678,  0.64470646,  0.72676599, -1.27600951],
       [-0.67292389,  1.18752045, -1.6269017 , -0.48702592, -0.59375431,
         1.18113476,  0.36214746, -2.77987669,  1.48336284,  0.7774676 ],
       [ 0.37551111, -0.91860429,  0.73402965,  2.7195555 ,  0.39736569,
         0.90035299, -1.32365555, -1.24325989,  0.67936718, -0.07808797],
       [-0.30963954,  1.49743247,  0.13928112, -1.19841276,  0.19511724,
         1.00190396,  2.45062236, -0.11285231

# Conditional Indexing

In [311]:
a=np.random.randint(11,100,(8,8))
a

array([[92, 60, 97, 96, 81, 73, 34, 89],
       [24, 53, 71, 36, 43, 83, 45, 78],
       [38, 11, 31, 86, 11, 69, 67, 70],
       [87, 55, 22, 27, 18, 11, 33, 99],
       [40, 54, 14, 36, 77, 11, 40, 16],
       [74, 61, 20, 81, 27, 79, 32, 90],
       [41, 96, 39, 90, 51, 14, 43, 82],
       [37, 81, 39, 89, 43, 50, 50, 14]])

In [312]:
a>50

array([[ True,  True,  True,  True,  True,  True, False,  True],
       [False,  True,  True, False, False,  True, False,  True],
       [False, False, False,  True, False,  True,  True,  True],
       [ True,  True, False, False, False, False, False,  True],
       [False,  True, False, False,  True, False, False, False],
       [ True,  True, False,  True, False,  True, False,  True],
       [False,  True, False,  True,  True, False, False,  True],
       [False,  True, False,  True, False, False, False, False]])

In [313]:
a[a>50]

array([92, 60, 97, 96, 81, 73, 89, 53, 71, 83, 78, 86, 69, 67, 70, 87, 55,
       99, 54, 77, 74, 61, 81, 79, 90, 96, 90, 51, 82, 81, 89])

In [314]:
a[a<50]

array([34, 24, 36, 43, 45, 38, 11, 31, 11, 22, 27, 18, 11, 33, 40, 14, 36,
       11, 40, 16, 20, 27, 32, 41, 39, 14, 43, 37, 39, 43, 14])

In [315]:
a[a<=50]

array([34, 24, 36, 43, 45, 38, 11, 31, 11, 22, 27, 18, 11, 33, 40, 14, 36,
       11, 40, 16, 20, 27, 32, 41, 39, 14, 43, 37, 39, 43, 50, 50, 14])

In [316]:
a[a==16]

array([16])

# Slicing in Multidimensional Arrays

In [317]:
a=np.random.randint(11,100,(8,8))
a

array([[51, 17, 30, 95, 78, 11, 60, 24],
       [46, 60, 96, 77, 30, 30, 32, 76],
       [35, 41, 91, 30, 95, 89, 63, 87],
       [14, 73, 44, 39, 56, 62, 84, 66],
       [96, 95, 93, 34, 31, 62, 79, 41],
       [70, 27, 19, 87, 84, 52, 70, 56],
       [58, 26, 21, 71, 35, 43, 13, 21],
       [45, 45, 97, 29, 20, 21, 92, 61]])

In [318]:
a[0:5]

array([[51, 17, 30, 95, 78, 11, 60, 24],
       [46, 60, 96, 77, 30, 30, 32, 76],
       [35, 41, 91, 30, 95, 89, 63, 87],
       [14, 73, 44, 39, 56, 62, 84, 66],
       [96, 95, 93, 34, 31, 62, 79, 41]])

In [319]:
a[:6]

array([[51, 17, 30, 95, 78, 11, 60, 24],
       [46, 60, 96, 77, 30, 30, 32, 76],
       [35, 41, 91, 30, 95, 89, 63, 87],
       [14, 73, 44, 39, 56, 62, 84, 66],
       [96, 95, 93, 34, 31, 62, 79, 41],
       [70, 27, 19, 87, 84, 52, 70, 56]])

In [320]:
a[-6:-1]

array([[35, 41, 91, 30, 95, 89, 63, 87],
       [14, 73, 44, 39, 56, 62, 84, 66],
       [96, 95, 93, 34, 31, 62, 79, 41],
       [70, 27, 19, 87, 84, 52, 70, 56],
       [58, 26, 21, 71, 35, 43, 13, 21]])

In [321]:
a[0:6,0:4]

array([[51, 17, 30, 95],
       [46, 60, 96, 77],
       [35, 41, 91, 30],
       [14, 73, 44, 39],
       [96, 95, 93, 34],
       [70, 27, 19, 87]])

In [323]:
a[10:3:-1,5:10]
#10 as the start index → clipped to 7 (last row).

#3 as the stop index → still valid (stop is exclusive).

array([[21, 92, 61],
       [43, 13, 21],
       [52, 70, 56],
       [62, 79, 41]])

In [326]:
# Take marks of two students in 5 subjects as input and calculate the absolute difference corresponding to each subject
student1=list(map(int,input("enter student1 marks: ").split())) #q)
student2=list(map(int,input("enter student2 marks: ").split()))

student1=np.array(student1)
student2=np.array(student2)
diff=np.abs(student1-student2)

diff

enter student1 marks: 22 10
enter student2 marks: 11


array([11,  1])